### ISSUE TITLE
Can we use "finite" list ?

### ISSUE THREAD

**Issue by mestartlearncode** [marcglasberg/indexed_list_view#10]
@marcglasberg 

Hi,

Can we use finite list ? becuase my existing code use `ListView.builder` with exact item....

or this plugin only support infinite list ?

thanks

**Comment by marcglasberg** [comment]
Please see this issue for possible solutions to your problem: https://github.com/flutter/flutter/issues/12319

**Comment by mestartlearncode** [comment]
> Please see this issue for possible solutions to your problem: [flutter/flutter#12319](https://github.com/flutter/flutter/issues/12319)

Hi thanks for reply, but those issue has opened for 2 years, but is it stil in progress/milestone or abandoned ?

**Comment by marcglasberg** [comment]
It's very much alive. If they'll ever going to do it I don't know.

**Comment by aytunch** [comment]
What is the reason behind not being able to use finite list? What needs to be done by Flutter? Also it seems like you made the harder part possible by making jumps in infinite lists. I am sure there must be a tricky way to make the code think our lost is infinite but stop scrolling before 0 and after list.lenght. Would a workaround work?

**Comment by marcglasberg** [comment]
@aytunch In my view the only thing that needs to be done by the Flutter team so that my widget could be finite is to let ListView have negative indexes (but still keep offset 0 at index 0). I will try to solve this problem in other ways to make the list finite, but I haven't had the time to try, and I don't know if I can make it anyway.
