### ISSUE TITLE
IndexedListView scrolls up by itself without stopping

### ISSUE THREAD

**Issue by radiKal07** [marcglasberg/indexed_list_view#22]
```
ParentWidget(
    child: IndexedListView.builder(
        // ...
    )
)
```

While scrolling up, I have a logic that as loads more data from my backend. When new data arrives `ParentWidget` is rebuild and this makes the `IndexedListView` scroll up by itself without stopping.
If I disable my logic to fetch new data then `ParentWidget` no longer gets rebuilt and the bug does not occur, so I think the issue happens when some parent of `IndexedListView` is rebuilt.

**Comment by marcglasberg** [comment]
I wouldn't really know what's going on by your description alone. Please try giving the IndexedListView a global key, and see if it fixes the problem.

If not, I can only hope to fix this if you create for me a minimum, reproducible example, following this guidelines: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by dokazhi** [comment]
@marcglasberg i have same issue, when u adding controller to the listview.builder, boundaries at top and bottom disappering.
![image](https://user-images.githubusercontent.com/24829504/79779902-f3477d80-835c-11ea-94b2-86e52460efd9.png)
![image](https://user-images.githubusercontent.com/24829504/79779918-f80c3180-835c-11ea-8a6c-3ac108c4cca1.png)
 like this

**Comment by marcglasberg** [comment]
@dokazhi I don't think this is what this issue is about. The other guy said the list was scrolling up **by itself** without stopping.

What you are saying is that the boundaries at top and bottom are disappering. Plase note, this is an **INFINITE** listView only, which means it actually has no top and bottom boundaries. 

If you need a list with boundaries, you probably should use this: https://pub.dev/packages/scrollable_positioned_list
