### ISSUE TITLE
item count issue

### ISSUE THREAD

**Issue by bilalidrees** [marcglasberg/indexed_list_view#27]
how to set fix item count in indexed_list_view.

**Comment by marcglasberg** [comment]
You can't. This is only for infinite lists. For finite, try this: https://pub.dev/packages/scrollable_positioned_list

**Comment by allComputableThings** [comment]
Sadly, ScrollablePositionList has many issues, not least, you can't adjust the position in increments by offset (/pixels).
This make it very difficult adjust the list position by key input (incrementing by the integer items indexes won't work for this).

And because IndexedListView can't handle finite lists, and also doesn't allow change-notifying the list index (following view changes by updating the offset), I think its impossible to use key input to scroll the list and prevent it scrolling into nothingness at the end of a finite list. I don't think this is resolvable with either ScrollablePositionList or IndexedListView.

**Comment by marcglasberg** [comment]
@stuz5000 `IndexedListView` is just for infinite lists, and this can't change. 

However, `ScrollablePositionList` in theory should be doing what you need. I saw that you filled an issue there. I also did (9 issues in total), and I'm hoping some day they get fixed.

**Comment by allComputableThings** [comment]
In theory -- but it doesn't expose what's needed, and there's been resistance to exposing it in other bugs. I'll keep looking.
