### ISSUE TITLE
List is reset when adding a new item

### ISSUE THREAD

**Issue by radiKal07** [marcglasberg/indexed_list_view#4]
After adding a new item in the list, then the list jumps to the initial start position.

**Comment by NickM-27** [comment]
Would there be a way to get the current position and then jump to that index after list is updated?

**Comment by marcglasberg** [comment]
I created this package just as proof of concept, to help the discussion at https://github.com/flutter/flutter/issues/12319. I was hoping someone there with more "slivers knowledge" than me would fix that issue and make this package obsolete. 

Really, I kept the version below 1.0 since this package is very limited at the moment. In a few months I will need to improve this package, since the project I'm working with will need it. Until then, I'm afraid I cannot help.

**Comment by marcglasberg** [comment]
Version 1.0.0 was released. See if it solved your problem. If not, please post some example code that demonstrates your problem. Thanks.
